### PR TITLE
Some useless stuff meant to make using the bot easier.

### PR DESCRIPTION
**Pull request by Dragonizedpizza**
Also why isn't this bot in the USSR?

### CODE REVIEW

**Comment by FC5570** [comment]
Because we don't need it

**Comment by Dragonizedpizza** [comment]
> Because we don't need it

Can use when chat dead and you wanna talk to someone

**Comment by FC5570** [comment]
We already have a lot of bots in ussr

**Comment by Dragonizedpizza** [comment]
> We already have a lot of bots in ussr

You have like 6 tops @FC5570 

Not alot ;-;

**Comment by FC5570** [comment]
I'll discuss with others and tell you.

**Comment by FC5570** [comment]
And thanks for the pr

**Pull request merged**
